name: LaTeX

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*'
  workflow_dispatch:

jobs:
  build_documents:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
        with:
          submodules: true
          token: ${{ secrets.GH_PAT }}

      - name: Compile LaTeX model appendix
        uses: xu-cheng/latex-action@v3
        with:
          root_file: "dsge-model-appendix.tex"
          work_in_root_file_dir: true

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: ncipollo/release-action@v1
        with:
          artifacts: "${{ github.workspace }}/dsge-model-appendix.pdf"
          generateReleaseNotes: true
          token: ${{ secrets.GH_PAT }}