name: Generate and Configure SSH Key

on:
  workflow_dispatch:

jobs:
  setup_ssh:
    runs-on: macos-latest
    steps:
      - name: Setup SSH keys
        run: |
          mkdir -p ~/.ssh
          cd ~/.ssh
          ssh-keygen -t ed25519 -f id_ed25519 -N ""
          cat ~/.ssh/id_ed25519.pub >> ~/.ssh/authorized_keys
          chmod 644 ~/.ssh/authorized_keys
          chmod 600 ~/.ssh/id_ed25519
          chmod 700 ~/.ssh
          touch ~/.ssh/config
          tee -a ~/.ssh/config > /dev/null <<EOT
          Host *
          AddKeysToAgent yes
          UseKeychain yes
          IdentityFile ~/.ssh/id_ed25519
          EOT
          eval "$(ssh-agent -s)"
          ssh-add -K ~/.ssh/id_ed25519
          ssh-keyscan -H localhost >> ~/.ssh/known_hosts
          ssh localhost "echo 'SSH connection successful'; exit"
